### ISSUE TITLE
root numpy for root 6.08.00 

### ISSUE THREAD

**Issue by smuzaffar** [rootpy/root_numpy#278]
We are trying to ise latest root 6.08.00 ( https://github.com/root-mirror/root/tree/v6-08-00-patches ) but noticed that root_numpy does not compile with latest changes in 6.08.00. We get compilation errors like
```
root_numpy/tmva/src/factory.pyx:28:25: error: 'class TMVA::Factory' has no member named 'AddEvent'
_factory.AddEvent("Signal", treetype, event[0], weight)
^
root_numpy/tmva/src/factory.pyx:30:25: error: 'class TMVA::Factory' has no member named 'AddEvent'
_factory.AddEvent("Background", treetype, event[0], weight)
^
root_numpy/tmva/src/factory.pyx: In function 'PyObject* __pyx_pf_13_libtmvanumpy_2factory_add_events_multiclass(PyObject*, PyObject*, PyArrayObject*, PyArrayObject*, PyArrayObject*, bool)':
root_numpy/tmva/src/factory.pyx:58:23: error: 'class TMVA::Factory' has no member named 'AddEvent'
_factory.AddEvent("Class_{0:d}".format(label), treetype, event[0], weight)
^
root_numpy/tmva/src/factory.pyx: In function 'PyObject* __pyx_pf_13_libtmvanumpy_4factory_add_events_regression(PyObject*, PyObject*, PyArrayObject*, PyArrayObject*, PyArrayObject*, bool)':
root_numpy/tmva/src/factory.pyx:87:23: error: 'class TMVA::Factory' has no member named 'AddEvent'
_factory.AddEvent("Regression", treetype, event[0], weight)
^
error: command 'gcc' failed with exit status 1
```

is  there any root numpy tag/branch which can go with latest root?

**Comment by kratsg** [comment]
https://github.com/root-mirror/root/search?utf8=%E2%9C%93&q=AddEvent it appears these still exist. Are you sure you're building ROOT with TMVA support enabled? The default is ON for sure, but it might have gotten built with it off?

**Comment by ndawe** [comment]
See our docs here (under the root_numpy.tmva header):

http://rootpy.github.io/root_numpy/reference/index.html

This should probably be in a more prominent spot, but we don't yet support the new TMVA interface as of 6.07. Also see #258

**Comment by ndawe** [comment]
To force root_numpy to exclude building the TMVA interface, do something like this:

```
NOTMVA=1 pip install --upgrade --user root_numpy
```

**Comment by smuzaffar** [comment]
Thanks @ndawe , setting NOTMVA=1 allowed us to build it without tmva.
